[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.15", features = ["derive"]}
crossterm = "0.24.0"
serde = { version = "1.0.140", features = ["derive"] }
syntect = "5.0.0"
toml = "0.5.9"
tui = "0.18.0"
